# Configuration options at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml

version: 2
updates:
- package-ecosystem: github-actions
  directories:
    - ".github/workflows/"
    - "/Templates/**/.github/workflows/"
  groups:
    External-Dependencies:
      applies-to: version-updates
      dependency-type: "production"
  ignore:
    - dependency-name: "microsoft/AL-Go-Actions/*"
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
